### ISSUE TITLE
Backslash sessions replication to elastic-search fails

### ISSUE THREAD

**Issue by ayalash** [getslash/backslash#571]
```
Traceback (most recent call last):
  File "/src/flask_app/tasks/replications.py", line 361, in do_elasticsearch_replication
    num_replicated, _ = es_helpers.bulk(es_index.get_client(), results)
  File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, *args, **kwargs):
  File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, *args, **kwargs)
  File "/root/.local/share/virtualenvs/src-NVTF7jWz/lib/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('5 document(s) failed to index.', ...)
```

**Comment by ayalash** [comment]
@maormarcus Please take a look

**Comment by ayalash** [comment]
@maormarcus I think that I found the problem, according to elasticsearch docs:
> A null value cannot be indexed or searched
In the full traceback (where I wrote '...') there are multiple 'None' values which we probably didn't handled

**Comment by ayalash** [comment]
My previous comment was incorrect, as @maormarcus found out, the problem was with the session metadata which is passed as dictionary instead of string.
